name: CI

on: [push]

jobs:
  check:
    name: Static code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install qiskit qiskit_aer
          pip install pylint autopep8
      - name: Run pylint
        run: PYTHONPATH=. pylint ./src
      - name: Run autopep8
        run: autopep8 -rd --exit-code ./src
