name: CI

on: [push]

jobs:
  check:
    name: Static code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pylint
        run: PYTHONPATH=. pylint ./src
      - name: Run autopep8
        run: autopep8 -rd --exit-code ./src
